spring:
  application:
    name: flex-sample-backend
  config:
    import:
  datasource:
    url: jdbc:tc:mysql:8.0.36:///test?serverTimezone=UTC&TC_REUSABLE=true&useUnicode=true&character_set_server=utf8mb4&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=false&preserveInstants=true&cacheDefaultTimezone=false&zeroDateTimeBehavior=convertToNull&jdbcCompliantTruncation=false&sessionVariables=sql_mode%3D'STRICT_ALL_TABLES'&rewriteBatchedStatements=true
    username: test
    password: test
  liquibase:
    change-log: classpath:/db/changelog/payroll/db.changelog-initial-schema-and-data.yaml

server:
  tomcat:
    mbeanregistry:
      enabled: true

#### Actuator 공통 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - loggers
  endpoint:
    health:
      probes:
        enabled: true

#### secrets
---

spring:
  config:
    activate:
      on-profile: local-dev

# local에서 server port 충돌을 피하기 위한 설정. gateway에 붙어야하면 이것을 기록해두는게 좋습니다
server:
  port: 12345

management:
  endpoints:
    web:
      exposure:
        include: '*'
