spring:
  application:
    name: flex-sample-backend

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&character_set_server=utf8mb4
    username: test
    password: test

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  tomcat:
    mbeanregistry:
      enabled: true

#### Actuator 공통 설정
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - loggers
  endpoint:
    health:
      probes:
        enabled: true

#### secrets
---

spring:
  config:
    activate:
      on-profile: local-dev

# local에서 server port 충돌을 피하기 위한 설정. gateway에 붙어야하면 이것을 기록해두는게 좋습니다
server:
  port: 12346

management:
  endpoints:
    web:
      exposure:
        include: '*'
