[versions]
kotlin = "2.1.21"
kotlinx-coroutine = "1.10.2"
crac = "1.5.0"

[plugins]
build-recipe = { id = "com.linecorp.build-recipe-plugin", version = "1.1.1" }
spring-boot = { id = "org.springframework.boot", version = "3.5.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.3.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutine-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutine" }
crac = { group = "org.crac", name = "crac", version.ref = "crac" }
